// weba/src/app/main/iclijmarket/iclijmarketbar.component.ts
import { Store, select } from '@ngrx/store';
import { Component, OnDestroy, OnInit, ViewChild } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
import { ActivationEnd, Router } from '@angular/router';
import { Observable, Subject } from 'rxjs';
import { filter, takeUntil, map } from 'rxjs/operators';
import { MatButtonModule } from '@angular/material/button';

import {
  ActionIncrement,
  ActionSetstartdate,
  ActionSetenddate,
  ActionGetcontent2,
  ActionGetcontentEvolve,
  ActionGetcontentDataset,
  ActionGetcontentCrosstest,
  ActionGetcontentFilter,
  ActionGetcontentAboveBelow,
  ActionGetcontentImprove,
  ActionGetcontentMachineLearning,
  ActionGetVerify,
  ActionGetVerifyLoop,
  ActionGetSingleMarket,
  ActionGetSingleMarketLoop,
  ActionGetImproveProfit,
  ActionGetImproveAboveBelow,
  ActionSetconfigvalue
} from '../main.actions';

import { MatSelectModule } from '@angular/material/select';
import { MatDatepickerModule } from '@angular/material/datepicker';

import { routeAnimations, TitleService } from '@app/core';
//import { tick } from '@angular/core';
import {
  State as BaseSettingsState,
  selectSettings,
  SettingsState
} from '@app/settings';

import { selectMain } from '../main.selectors';
import { MainState } from '../main.state';
import { State as BaseMainState } from '../main.state';
import { selectAuth } from '@app/core/auth/auth.selectors';
import {
  ActionGetmarkets,
  ActionSetmarket,
  ActionSetmlmarket
} from '../main.actions';

interface State extends BaseSettingsState, BaseMainState {}

@Component({
  selector: 'iclijmarketbar',
  templateUrl: './iclijmarketbar.component.html',
  //styleUrls: ['./main.component.scss'],
  animations: [routeAnimations]
})
export class IclijMarketbarComponent implements OnInit, OnDestroy {
  private unsubscribe$: Subject<void> = new Subject<void>();
  private isAuthenticated$: Observable<boolean>;

  main: MainState;

  markets: Array<string>;

  constructor(
    private store: Store<State>,
    private router: Router,
    private titleService: TitleService,
    private translate: TranslateService
  ) {}

  ngOnInit(): void {
    this.translate.setDefaultLang('en');
    this.subscribeToMain();
    //this.subscribeToSettings();
    this.subscribeToRouterEvents();
    this.isAuthenticated$ = this.store.pipe(
      select(selectAuth),
      map(auth => auth.isAuthenticated)
    );
    this.store.dispatch(new ActionGetmarkets());
    const value = new Date().toISOString();
    this.store.dispatch(new ActionSetenddate({ enddate: value }));
  }

  ngOnDestroy(): void {
    this.unsubscribe$.next();
    this.unsubscribe$.complete();
  }

  private subscribeToRouterEvents() {
    this.titleService.setTitle(
      this.router.routerState.snapshot.root,
      this.translate
    );
    this.router.events
      .pipe(
        filter(event => event instanceof ActivationEnd),
        map((event: ActivationEnd) => event.snapshot),
        takeUntil(this.unsubscribe$)
      )
      .subscribe(snapshot =>
        this.titleService.setTitle(snapshot, this.translate)
      );
  }

  private subscribeToMain() {
    this.store
      .pipe(select(selectMain), takeUntil(this.unsubscribe$))
      .subscribe((main: MainState) => {
        this.main = main;
        this.setMarkets(main);
      });
  }

  private setMarkets(main: MainState) {
    console.log(main);
    this.markets = main.markets;
  }

  //@ViewChild('increment') increment;

  changemarket($event) {
    console.log('market');
    console.log($event);
    console.log(this);
    this.store.dispatch(new ActionSetmarket({ market: $event.value }));
    this.store.dispatch(new ActionSetconfigvalue(['market', $event.value]));
    //this.increment.focus();
  }
  changemlmarket($event) {
    console.log('market');
    console.log($event);
    console.log(this);
    this.store.dispatch(new ActionSetmlmarket({ mlmarket: $event.value }));
    this.store.dispatch(new ActionSetconfigvalue(['mlmarket', $event.value]));
    //this.increment.focus();
  }

  resetmarket($event) {
    console.log('market');
    console.log($event);
    console.log(this);
    this.store.dispatch(new ActionSetmarket({ market: null }));
    this.store.dispatch(new ActionSetconfigvalue(['market', null]));
    //this.increment.focus();
  }

  resetmlmarket($event) {
    console.log('market');
    console.log($event);
    console.log(this);
    this.store.dispatch(new ActionSetmlmarket({ mlmarket: null }));
    this.store.dispatch(new ActionSetconfigvalue(['mlmarket', null]));
    //this.increment.focus();
  }

  handleStartDateChange($event) {
    console.log($event);
    this.store.dispatch(new ActionSetstartdate({ startdate: $event.value }));
    this.store.dispatch(new ActionSetconfigvalue(['startdate', $event.value]));
  }

  handleEndDateChange($event) {
    console.log($event);
    this.store.dispatch(new ActionSetenddate({ enddate: $event.value }));
    this.store.dispatch(new ActionSetconfigvalue(['enddate', $event.value]));
  }

  resetStartDate($event) {
    console.log($event);
    this.store.dispatch(new ActionSetstartdate({ startdate: null }));
    this.store.dispatch(new ActionSetconfigvalue(['startdate', null]));
  }

  resetEndDate($event) {
    console.log($event);
    this.store.dispatch(new ActionSetenddate({ enddate: null }));
    this.store.dispatch(new ActionSetconfigvalue(['enddate', null]));
  }

  getContent($event) {
    console.log($event);
    console.log(this);
    this.store.dispatch(new ActionGetcontent2(this.main.config2));
  }

  getContentMachineLearning($event) {
    console.log($event);
    this.store.dispatch(new ActionGetcontentMachineLearning(this.main.config2));
  }

  getContentEvolve($event) {
    console.log($event);
    this.store.dispatch(new ActionGetcontentEvolve(this.main.config2));
  }

  getContentDataset($event) {
    console.log($event);
    this.store.dispatch(new ActionGetcontentDataset(this.main.config2));
  }

  getContentCrosstest($event) {
    console.log($event);
    this.store.dispatch(new ActionGetcontentCrosstest(this.main.config2));
  }

  getContentFilter($event) {
    console.log($event);
    this.store.dispatch(new ActionGetcontentFilter(this.main.config2));
  }

  getContentAboveBelow($event) {
    console.log($event);
    this.store.dispatch(new ActionGetcontentAboveBelow(this.main.config2));
  }

  getContentImprove($event) {
    console.log($event);
    this.store.dispatch(new ActionGetcontentImprove(this.main.config2));
  }

  getContentImproveAboveBelow($event) {
    console.log($event);
    this.store.dispatch(new ActionGetImproveAboveBelow(this.main.config2));
  }

  getVerify($event) {
    console.log($event);
    this.store.dispatch(new ActionGetVerify(this.main.config2));
  }

  getVerifyLoop($event) {
    console.log($event);
    this.store.dispatch(new ActionGetVerifyLoop(this.main.config2));
  }

  getSingleMarket($event) {
    console.log($event);
    this.store.dispatch(new ActionGetSingleMarket(this.main.config2));
  }

  getSingleMarketLoop($event) {
    console.log($event);
    this.store.dispatch(new ActionGetSingleMarketLoop(this.main.config2));
  }

  getImproveProfit($event) {
    console.log($event);
    this.store.dispatch(new ActionGetImproveProfit(this.main.config2));
  }

}

  <h1>marketbar</h1>
  <mat-select placeholder="Get market" (selectionChange)="changemarket($event)">
    <mat-option *ngFor="let market of markets" [value]="market">{{ market }}</mat-option>
  </mat-select>
  <mat-select placeholder="Get ml market" (selectionChange)="changemlmarket($event)">
    <mat-option *ngFor="let market of markets" [value]="market">{{ market }}</mat-option>
  </mat-select>
  <button class="mat-raised-button" (click)="resetmarket($event)">Reset market</button>
  <button class="mat-raised-button" (click)="resetmlmarket($event)">Reset ml market</button>
   <input matInput [matDatepicker]="startpicker" placeholder="Start date" (dateChange)=handleStartDateChange($event)>
   <mat-datepicker-toggle matSuffix [for]="startpicker"></mat-datepicker-toggle>
   <mat-datepicker #startpicker></mat-datepicker>
   <input matInput [matDatepicker]="endpicker" placeholder="End date" (dateChange)=handleEndDateChange($event)>
   <mat-datepicker-toggle matSuffix [for]="endpicker"></mat-datepicker-toggle>
   <mat-datepicker #endpicker></mat-datepicker>
   <br/>
  <button class="mat-raised-button" (click)="resetStartDate($event)">Reset start date</button>
  <button class="mat-raised-button" (click)="resetEndDate($event)">Reset end date</button>
  <br/>
  <button class="mat-raised-button" (click)="getContent($event)">Get find profit data</button>
  <button class="mat-raised-button" (click)="getContentMachineLearning($event)">Get machine learning data</button>
  <button class="mat-raised-button" (click)="getContentEvolve($event)">Get evolve data</button>
  <button class="mat-raised-button" (click)="getContentImprove($event)">Get improve profit data</button>
  <button class="mat-raised-button" (click)="getContentDataset($event)">Get dataset data</button>
  <button class="mat-raised-button" (click)="getContentCrosstest($event)">Get crosstest data</button>
  <button class="mat-raised-button" (click)="getContentFilter($event)">Get filter data</button>
  <button class="mat-raised-button" (click)="getContentAboveBelow($event)">Get above below data</button>
  <br>
  <button class="mat-raised-button" (click)="getVerify($event)">Run and get find profit verification data</button>
  <button class="mat-raised-button" (click)="getVerifyLoop($event)">Run and get find profit verification data loop</button>
  <br/>
  <button class="mat-raised-button" (click)="getSingleMarket($event)">Run and get find profit data</button>
  <button class="mat-raised-button" (click)="getSingleMarketLoop($event)">Run and get find profit data loop</button>
  <br/>
  <button class="mat-raised-button" (click)="getImproveProfit($event)">Run and get single improve profit data</button>
  <button class="mat-raised-button" (click)="getContentImproveAboveBelow($event)">Run and get single improve above below data</button>

// webr/src/js/common/components/IclijMarket/IclijMarketBar.jsx
import React, { PureComponent } from 'react';

import { Client, ConvertToSelect } from '../util'
import Select from 'react-select';
import { DropdownButton, MenuItem, ButtonToolbar, Button, Nav, Navbar, NavItem, FormControl } from 'react-bootstrap';
import { ServiceParam, ServiceResult } from '../../types/main'
import DatePicker from 'react-datepicker';

class IclijMarketBar extends PureComponent {
    type;
    constructor(props) {
	super(props);
	console.log("here");
	console.log(props);
	console.log(this.props);
	var value = new Date().toISOString();
	console.log(this.props);
	this.props.setenddate(value);
	console.log("here");
	//console.log(this.state.markets);
    }

    /*
      componentDidMount() {
      this.props.getMarkets();
      }
    */

    handleYearChange = (e) => {
	console.log(e);
	console.log(this);
	const value = e.value;
	var result;
    }

    handleChange(event, props) {
	console.log(event);
	console.log(event.value);
	console.log(props);
	//this.props.setmarket({market: event.value});
	props.setimarket(event.value);
	//props.setconfigvalue([ 'market', event.value ]);
	props.seticonfigvalue([ 'market', event.value ]);
    }
    
    handleChangeML(event, props) {
	console.log(event);
	console.log(event.value);
	console.log(props);
	//this.props.setmarket({market: event.value});
	props.setimarket(event.value);
	//props.setconfigvalue([ 'market', event.value ]);
	props.seticonfigvalue([ 'mlmarket', event.value ]);
    }
    
    resetMarket(event, props) {
	console.log(event);
	console.log(event.value);
	console.log(props);
	//this.props.setmarket({market: event.value});
	props.setimarket(null);
	//props.setconfigvalue([ 'market', event.value ]);
	props.seticonfigvalue([ 'market', null ]);
    }
    
    resetML(event, props) {
	console.log(event);
	console.log(event.value);
	console.log(props);
	//this.props.setmarket({market: event.value});
	props.setmlmarket(null);
	//props.setconfigvalue([ 'market', event.value ]);
	props.seticonfigvalue([ 'mlmarket', null ]);
    }
    
    handleStartDateChange(event, props) {
	console.log(event);
	console.log(props);
	props.setstartdate(event);
        props.seticonfigvalue([ 'startdate', event ]);
    }
    
    handleEndDateChange(event, props) {
	console.log(event);
	console.log(props);
	props.setenddate(event);
        props.seticonfigvalue([ 'enddate', event ]);
    }
    
    resetStartDate(event, props) {
	console.log(event);
	console.log(props);
	props.setstartdate(null);
        props.seticonfigvalue([ 'startdate', null ]);
    }
    
    resetEndDate(event, props) {
	console.log(event);
	console.log(props);
	props.setenddate(null);
        props.seticonfigvalue([ 'enddate', null ]);
    }
    
    getContent(event, props) {
	console.log(event);
	console.log(props);
	console.log(props.main.imarket);
	props.getcontent2(props.main.iconfig, props.main.imarket, props);
    }
    
    getContent(event, props) {
	props.getcontent(props.main.iconfig, props.main.imarket, props);
    }
    
    getContentEvolve(event, props) {
	props.getcontentevolve(props.main.iconfig, props.main.imarket, props);
    }
    
    getContentDataset(event, props) {
	props.getcontentdataset(props.main.iconfig, props.main.imarket, props);
    }
    
    getContentCrosstest(event, props) {
	props.getcontentcrosstest(props.main.iconfig, props.main.imarket, props);
    }
    
    getContentImprove(event, props) {
	props.getcontentimprove(props.main.iconfig, props.main.imarket, props);
    }
    
    getContentMachineLearning(event, props) {
	props.getcontentmachinelearning(props.main.iconfig, props.main.imarket, props);
    }
    
    getContentFilter(event, props) {
	props.getcontentfilter(props.main.iconfig, props.main.imarket, props);
    }
    
    getContentAboveBelow(event, props) {
	props.getcontentabovebelow(props.main.iconfig, props.main.imarket, props);
    }
    
    getSingleMarket(event, props) {
	props.getsinglemarket(props.main.iconfig, props.main.imarket, props, false);
    }
    
    getSingleMarketLoop(event, props) {
	props.getsinglemarket(props.main.iconfig, props.main.imarket, props, true);
    }
    
    getImproveProfit(event, props) {
	props.getimproveprofit(props.main.iconfig, props.main.imarket, props);
    }
    
    getImproveAboveBelow(event, props) {
	props.getimproveabovebelow(props.main.iconfig, props.main.imarket, props);
    }
    
    getVerify(event, props) {
	props.getverify(props.main.iconfig, props.main.imarket, props, false);
    }
    
    getVerifyLoop(event, props) {
	props.getverify(props.main.iconfig, props.main.imarket, props, true);
    }
    
    render() {
	const { main } = this.props;
	console.log(main);
	const markets = main && main.markets ? main.markets : null;
	const startdate = main && main.startdate ? main.startdate : null;
	const enddate = main && main.enddate ? main.enddate : null;
	console.log(process.env);
	console.log(process.porti);
	console.log(main.imarket);
	console.log(main.iconfig);
	//console.log(main.config.get('market'));
	console.log(markets);
	console.log(startdate);
	console.log(enddate);
	var markets2 = ConvertToSelect.convert2(markets);
	console.log(markets2);
	return (
	    <div>
	      <Navbar>
		<Navbar.Header>
		  <Navbar.Brand>
		    <a href="#home">{this.type}</a>
		  </Navbar.Brand>
		</Navbar.Header>
		<Nav>
		  <NavItem eventKey={1} href="#">
		    Name
		    <Select options="[{size:'5'}]"
			    onChange={e => this.handleChange(e, this.props)}
		      options={markets2}
		      />
		  </NavItem>
		  <NavItem eventKey={1} href="#">
		    Name
		    <Select options="[{size:'5'}]"
			    onChange={e => this.handleChangeML(e, this.props)}
		      options={markets2}
		      />
		  </NavItem>
		  <NavItem eventKey={1} href="#">
		    Name
		    <Select options="[{size:'5'}]"
			    onChange={e => this.resetMarket(e, this.props)}
		      options={markets2}
		      />
		  </NavItem>
		  <NavItem eventKey={1} href="#">
		    Name
		    <Select options="[{size:'5'}]"
			    onChange={e => this.resetML(e, this.props)}
		      options={markets2}
		      />
		  </NavItem>
		  <NavItem eventKey={2} href="#">
		    Start date
		    <DatePicker id="startdatepicker" value={startdate} onChange={e => this.handleStartDateChange(e, this.props)}/>
		  </NavItem>
		  <NavItem eventKey={3} href="#">
		    End date
		    <DatePicker id="enddatepicker" value={enddate} onChange={e => this.handleEndDateChange(e, this.props)}/>
		  </NavItem>
		  <NavItem eventKey={4} href="#">
		    <Button
		      bsStyle="primary"
		      onClick={ (e) => this.resetStartDate(e, this.props) }
		      >
		      Reset start date
		    </Button>
		  </NavItem>
		  <NavItem eventKey={5} href="#">
		    <Button
		      bsStyle="primary"
		      onClick={ (e) => this.resetEndDate(e, this.props) }
		      >
		      Reset end date
		    </Button>
		  </NavItem>
		</Nav>
	      </Navbar>
	      <Navbar>
		<Navbar.Header>
		  <Navbar.Brand>
		    <a href="#home">{this.type}</a>
		  </Navbar.Brand>
		</Navbar.Header>
		<Nav>
		  <NavItem eventKey={6} href="#">
		    <Button
		      bsStyle="primary"
		      onClick={
			  (e) => this.getContent(e, this.props)
		      }
		      >
		      Get find profit data
		    </Button>
		  </NavItem>
		  <NavItem eventKey={6} href="#">
		    <Button
		      bsStyle="primary"
		      onClick={
			  (e) => this.getContentMachineLearning(e, this.props)
		      }
		      >
		      Get machine learning data
		    </Button>
		  </NavItem>
		  <NavItem eventKey={6} href="#">
		    <Button
		      bsStyle="primary"
		      onClick={
			  (e) => this.getContentEvolve(e, this.props)
		      }
		      >
		      Get evolve data
		    </Button>
		  </NavItem>
		  <NavItem eventKey={6} href="#">
		    <Button
		      bsStyle="primary"
		      onClick={
			  (e) => this.getContentImprove(e, this.props)
		      }
		      >
		      Get improve profit data
		    </Button>
		  </NavItem>
		  <NavItem eventKey={6} href="#">
		    <Button
		      bsStyle="primary"
		      onClick={
			  (e) => this.getContentDataset(e, this.props)
		      }
		      >
		      Get dataset data
		    </Button>
		  </NavItem>
		  <NavItem eventKey={6} href="#">
		    <Button
		      bsStyle="primary"
		      onClick={
			  (e) => this.getContentCrosstest(e, this.props)
		      }
		      >
		      Get crosstest data
		    </Button>
		  </NavItem>
		  <NavItem eventKey={6} href="#">
		    <Button
		      bsStyle="primary"
		      onClick={
			  (e) => this.getContentFilter(e, this.props)
		      }
		      >
		      Get filter data
		    </Button>
		  </NavItem>
		  <NavItem eventKey={7} href="#">
		    <Button
		      bsStyle="primary"
		      onClick={
			  (e) => this.getContentAboveBelow(e, this.props)
		      }
		      >
		      Get above below data
		    </Button>
		  </NavItem>
		</Nav>
	      </Navbar>
	      <Navbar>
		<Navbar.Header>
		  <Navbar.Brand>
		    <a href="#home">{this.type}</a>
		  </Navbar.Brand>
		</Navbar.Header>
		<Nav>
		  <NavItem eventKey={6} href="#">
		    <Button
		      bsStyle="primary"
		      onClick={
			  (e) => this.getVerify(e, this.props)
		      }
		      >
		      Run and get find profit verification data
		    </Button>
		  </NavItem>
		  <NavItem eventKey={6} href="#">
		    <Button
		      bsStyle="primary"
		      onClick={
			  (e) => this.getVerifyLoop(e, this.props)
		      }
		      >
		      Run and get find profit verification data loop
		    </Button>
		  </NavItem>
		</Nav>
	      </Navbar>
	      <Navbar>
		<Navbar.Header>
		  <Navbar.Brand>
		    <a href="#home">{this.type}</a>
		  </Navbar.Brand>
		</Navbar.Header>
		<Nav>
		  <NavItem eventKey={6} href="#">
		    <Button
		      bsStyle="primary"
		      onClick={
			  (e) => this.getSingleMarket(e, this.props)
		      }
		      >
		      Run and get find profit data
		    </Button>
		  </NavItem>
		  <NavItem eventKey={6} href="#">
		    <Button
		      bsStyle="primary"
		      onClick={
			  (e) => this.getSingleMarketLoop(e, this.props)
		      }
		      >
		      Run and get find profit data loop
		    </Button>
		  </NavItem>
		</Nav>
	      </Navbar>
	      <Navbar>
		<Navbar.Header>
		  <Navbar.Brand>
		    <a href="#home">{this.type}</a>
		  </Navbar.Brand>
		</Navbar.Header>
		<Nav>
		  <NavItem eventKey={6} href="#">
		    <Button
		      bsStyle="primary"
		      onClick={
			  (e) => this.getImprove(e, this.props)
		      }
		      >
		      Run and get single improve profit data
		    </Button>
		  </NavItem>
		  <NavItem eventKey={7} href="#">
		    <Button
		      bsStyle="primary"
		      onClick={
			  (e) => this.getImproveAboveBelow(e, this.props)
		      }
		      >
		      Run and get single improve above below data
		    </Button>
		  </NavItem>
		</Nav>
	      </Navbar>
	    </div>
	);
    }
}

export default IclijMarketBar;
